import hashlib
import re
import uuid
from typing import Dict, Iterable, List, Optional, Tuple

from sqlalchemy.exc import SQLAlchemyError

from db.database import SessionLocal
from models.order_dataset import OrderDataset
from models.raw_chat import RawChat


_MONTH_MAP = {
    "JAN": 1,
    "JANUARI": 1,
    "FEB": 2,
    "FEBRUARI": 2,
    "MAR": 3,
    "MARET": 3,
    "APR": 4,
    "APRIL": 4,
    "MEI": 5,
    "JUN": 6,
    "JUNI": 6,
    "JUL": 7,
    "JULI": 7,
    "AGS": 8,
    "AGUSTUS": 8,
    "AUG": 8,
    "SEP": 9,
    "SEPT": 9,
    "SEPTEMBER": 9,
    "OKT": 10,
    "OKTOBER": 10,
    "OCT": 10,
    "NOV": 11,
    "NOVEMBER": 11,
    "DES": 12,
    "DESEMBER": 12,
    "DEC": 12,
}


def _clean(value) -> str:
    if value is None:
        return ""
    return str(value).strip()


def generate_chat_hash(chat_text: str) -> str:
    normalized = (chat_text or "").strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def extract_month_year_from_tgl_muat(tgl_muat: Optional[str]) -> Tuple[Optional[int], Optional[int]]:
    if not tgl_muat:
        return None, None

    text = str(tgl_muat).strip().upper()

    # Pattern: DD/MM/YYYY or DD-MM-YYYY
    m = re.search(r"\b\d{1,2}[/-](\d{1,2})[/-](\d{2,4})\b", text)
    if m:
        month = int(m.group(1))
        year = int(m.group(2))
        if year < 100:
            year += 2000
        return month, year

    # Pattern: DD MON YYYY (e.g. 05 FEBRUARI 2026)
    m = re.search(r"\b\d{1,2}\s+([A-Z]+)\s+(\d{2,4})\b", text)
    if m:
        month = _MONTH_MAP.get(m.group(1))
        year = int(m.group(2))
        if year < 100:
            year += 2000
        return month, year

    return None, None


def _to_uuid(value):
    if value is None:
        return None
    if isinstance(value, uuid.UUID):
        return value
    try:
        return uuid.UUID(str(value))
    except Exception:
        return None


def prepare_chat_for_parsing(chat_text: str) -> Tuple[bool, Optional[uuid.UUID]]:
    """
    Deduplication gate before parser runs.

    Returns:
        (should_parse, raw_chat_id)
    """
    chat_hash = generate_chat_hash(chat_text)
    session = SessionLocal()
    try:
        existing = session.query(RawChat).filter(RawChat.chat_hash == chat_hash).first()
        if existing:
            return False, existing.id

        row = RawChat(chat_hash=chat_hash, chat_text=chat_text)
        session.add(row)
        session.commit()
        session.refresh(row)
        return True, row.id
    except SQLAlchemyError:
        session.rollback()
        raise
    finally:
        session.close()


def _iter_rows(parsed_rows: Iterable[Dict]):
    # Support list[dict] and pandas.DataFrame without importing pandas explicitly.
    if hasattr(parsed_rows, "to_dict"):
        return parsed_rows.to_dict(orient="records")
    return parsed_rows


def _normalize_row_keys(row: Dict) -> Dict:
    if not isinstance(row, dict):
        return {
            "job_number": "",
            "tgl_ro": "",
            "tgl_muat": "",
            "pickup": "",
            "tujuan": "",
            "no_plat": "",
            "type_truck": "",
            "driver": "",
            "kontak_driver": "",
            "status_unit": "",
        }

    # Support parser-style keys and Office table keys.
    return {
        "job_number": _clean(row.get("job_number", row.get("Job Number", ""))),
        "tgl_ro": _clean(row.get("tgl_ro", row.get("Tgl RO", ""))),
        "tgl_muat": _clean(row.get("tgl_muat", row.get("Tgl Muat", ""))),
        "pickup": _clean(row.get("pickup", row.get("Pickup", ""))),
        "tujuan": _clean(row.get("tujuan", row.get("Tujuan", ""))),
        "no_plat": _clean(row.get("no_plat", row.get("No. Plat", ""))),
        "type_truck": _clean(row.get("type_truck", row.get("Type Truck", ""))),
        "driver": _clean(row.get("driver", row.get("Driver", ""))),
        "kontak_driver": _clean(row.get("kontak_driver", row.get("Kontak Driver", ""))),
        "status_unit": _clean(row.get("status_unit", row.get("status_unit", ""))),
    }


def _row_base_key(norm_row: Dict) -> str:
    # Deliberately ignore job_number; it can be regenerated by UI mode.
    fields = [
        norm_row.get("tgl_ro", "").upper(),
        norm_row.get("tgl_muat", "").upper(),
        norm_row.get("pickup", "").upper(),
        norm_row.get("tujuan", "").upper(),
        norm_row.get("no_plat", "").upper(),
        norm_row.get("type_truck", "").upper(),
        norm_row.get("driver", "").upper(),
        norm_row.get("kontak_driver", "").upper(),
        norm_row.get("status_unit", "").upper(),
    ]
    return "|".join(fields)


def _build_row_hash(base_key: str, occurrence: int) -> str:
    payload = f"{base_key}|occ:{occurrence}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def save_parsed_rows(raw_chat_id, parsed_rows: Iterable[Dict]) -> int:
    """
    Persist parser output rows without changing parser field names.
    Expected row keys:
      job_number, tgl_ro, tgl_muat, pickup, tujuan,
      no_plat, type_truck, driver, kontak_driver, status_unit
    """
    session = SessionLocal()
    inserted = 0
    occurrence_map: Dict[str, int] = {}
    raw_chat_uuid = _to_uuid(raw_chat_id)

    try:
        rows = list(_iter_rows(parsed_rows))
        for raw_row in rows:
            norm = _normalize_row_keys(raw_row)
            tgl_muat = norm.get("tgl_muat")
            month_segment, year_segment = extract_month_year_from_tgl_muat(tgl_muat)

            base_key = _row_base_key(norm)
            occurrence_map[base_key] = occurrence_map.get(base_key, 0) + 1
            occ = occurrence_map[base_key]
            row_hash = _build_row_hash(base_key, occ)

            exists = session.query(OrderDataset.id).filter(OrderDataset.row_hash == row_hash).first()
            if exists:
                continue

            rec = OrderDataset(
                raw_chat_id=raw_chat_uuid,
                row_hash=row_hash,
                job_number=norm.get("job_number"),
                tgl_ro=norm.get("tgl_ro"),
                tgl_muat=tgl_muat,
                pickup=norm.get("pickup"),
                tujuan=norm.get("tujuan"),
                no_plat=norm.get("no_plat"),
                type_truck=norm.get("type_truck"),
                driver=norm.get("driver"),
                kontak_driver=norm.get("kontak_driver"),
                status_unit=norm.get("status_unit"),
                month_segment=month_segment,
                year_segment=year_segment,
            )
            session.add(rec)
            inserted += 1

        session.commit()
        return inserted
    except SQLAlchemyError:
        session.rollback()
        raise
    finally:
        session.close()


def load_all_order_rows() -> List[Dict]:
    session = SessionLocal()
    try:
        rows = (
            session.query(OrderDataset)
            .order_by(OrderDataset.created_at.asc(), OrderDataset.id.asc())
            .all()
        )
        return [
            {
                "job_number": _clean(r.job_number),
                "tgl_ro": _clean(r.tgl_ro),
                "tgl_muat": _clean(r.tgl_muat),
                "pickup": _clean(r.pickup),
                "tujuan": _clean(r.tujuan),
                "no_plat": _clean(r.no_plat),
                "type_truck": _clean(r.type_truck),
                "driver": _clean(r.driver),
                "kontak_driver": _clean(r.kontak_driver),
                "status_unit": _clean(r.status_unit),
            }
            for r in rows
        ]
    except SQLAlchemyError:
        return []
    finally:
        session.close()

def reset_all_data() -> Dict[str, int]:
    """
    Reset seluruh data parser yang tersimpan agar database kembali kosong.
    """
    session = SessionLocal()
    try:
        deleted_order_rows = session.query(OrderDataset).delete(synchronize_session=False)
        deleted_raw_chats = session.query(RawChat).delete(synchronize_session=False)
        session.commit()
        return {
            "order_dataset_deleted": int(deleted_order_rows or 0),
            "raw_chats_deleted": int(deleted_raw_chats or 0),
        }
    except SQLAlchemyError:
        session.rollback()
        raise
    finally:
        session.close()
